name: nightly_v21

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 2-6'

jobs:  
  trigger-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push nightly tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Get the latest release tag
          DESCRIBE=$(git tag -l --sort=-v:refname | grep -v nightly | head -n 1)
          MAJOR_VERSION=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[1]}')
          MINOR_VERSION=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[2]}')
          PATCH_VERSION=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[3]}')
          PATCH_NUMBER=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[4]}')
          TAG="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}.${PATCH_NUMBER}.nightly.$(date +'%Y%m%d')"
          git tag -a $TAG -m "$TAG: nightly build"
          git push origin $TAG
