name: nightly_v21

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 2-6'

jobs:  
  trigger-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push nightly tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Get the latest release tag
          DESCRIBE=$(git tag -l --sort=-v:refname | grep -v nightly | head -n 1)
          MAJOR_VERSION=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[1]}')
          MINOR_VERSION=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[2]}')
          PATCH_VERSION=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[3]}')
          PATCH_NUMBER=$(echo $DESCRIBE | awk '{split($0,a,"."); print a[4]}')
          TAG="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}.${PATCH_NUMBER}.nightly.$(date +'%Y%m%d')"
          git tag -a $TAG -m "$TAG: nightly build"
          git push origin $TAG
      - name: 'Clean up nightly releases'
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 5
          delete_tags: true
          delete_tag_pattern: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.WEAVE_ASSURED_GHCR_BOT_TOKEN  }}
      - name: 'Delete nightly containers older than a week'
        uses: snok/container-retention-policy@v2
        with:
          image-names: flux-cli, source-controller, kustomize-controller, helm-controller, notification-controller, image-reflector-controller, image-automation-controller
          cut-off: 1 week ago UTC
          account-type: org
          org-name: weaveworks
          keep-at-least: 5
          token: ${{ secrets.WEAVE_ASSURED_GHCR_BOT_TOKEN  }}
          filter-tags: '*-nightly*'
