name: scan

on:
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * 3'

permissions:
  contents: read

jobs:
  scan-trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get image version
        id: version
        run: |
          ln -s patches-flux-v21 patches-flux
          source ./patches-flux/VERSION
          if [[ "$FLUX2_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            FLUX2_VERSION=${FLUX2_BASE_VERSION}-${FLUX2_SUFFIX_VERSION}
          else
            FLUX2_VERSION=${FLUX2_BASE_VERSION}-wa
          fi
          if [[ "$SOURCE_CONTROLLER_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            SOURCE_CONTROLLER_VERSION=${SOURCE_CONTROLLER_BASE_VERSION}-${SOURCE_CONTROLLER_SUFFIX_VERSION}
          else
            SOURCE_CONTROLLER_VERSION=${SOURCE_CONTROLLER_BASE_VERSION}-wa
          fi
          if [[ "$KUSTOMIZE_CONTROLLER_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            KUSTOMIZE_CONTROLLER_VERSION=${KUSTOMIZE_CONTROLLER_BASE_VERSION}-${KUSTOMIZE_CONTROLLER_SUFFIX_VERSION}
          else
            KUSTOMIZE_CONTROLLER_VERSION=${KUSTOMIZE_CONTROLLER_BASE_VERSION}-wa
          fi
          if [[ "$HELM_CONTROLLER_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            HELM_CONTROLLER_VERSION=${HELM_CONTROLLER_BASE_VERSION}-${HELM_CONTROLLER_SUFFIX_VERSION}
          else
            HELM_CONTROLLER_VERSION=${HELM_CONTROLLER_BASE_VERSION}-wa
          fi
          if [[ "$NOTIFICATION_CONTROLLER_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            NOTIFICATION_CONTROLLER_VERSION=${NOTIFICATION_CONTROLLER_BASE_VERSION}-${NOTIFICATION_CONTROLLER_SUFFIX_VERSION}
          else
            NOTIFICATION_CONTROLLER_VERSION=${NOTIFICATION_CONTROLLER_BASE_VERSION}-wa
          fi
          if [[ "$IMAGE_REFLECTOR_CONTROLLER_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            IMAGE_REFLECTOR_CONTROLLER_VERSION=${IMAGE_REFLECTOR_CONTROLLER_BASE_VERSION}-${IMAGE_REFLECTOR_CONTROLLER_SUFFIX_VERSION}
          else
            IMAGE_REFLECTOR_CONTROLLER_VERSION=${IMAGE_REFLECTOR_CONTROLLER_BASE_VERSION}-wa
          fi
          if [[ "$IMAGE_AUTOMATION_CONTROLLER_SUFFIX_VERSION" =~ ^wa[.][0-9]+$ ]]; then
            IMAGE_AUTOMATION_CONTROLLER_VERSION=${IMAGE_AUTOMATION_CONTROLLER_BASE_VERSION}-${IMAGE_AUTOMATION_CONTROLLER_SUFFIX_VERSION}
          else
            IMAGE_AUTOMATION_CONTROLLER_VERSION=${IMAGE_AUTOMATION_CONTROLLER_BASE_VERSION}-wa
          fi
          unlink patches-flux
          echo "iac=${IMAGE_AUTOMATION_CONTROLLER_VERSION}" >> $GITHUB_OUTPUT
          echo "irc=${IMAGE_REFLECTOR_CONTROLLER_VERSION}" >> $GITHUB_OUTPUT
          echo "nc=${NOTIFICATION_CONTROLLER_VERSION}" >> $GITHUB_OUTPUT
          echo "hc=${HELM_CONTROLLER_VERSION}" >> $GITHUB_OUTPUT
          echo "kc=${KUSTOMIZE_CONTROLLER_VERSION}" >> $GITHUB_OUTPUT
          echo "sc=${SOURCE_CONTROLLER_VERSION}" >> $GITHUB_OUTPUT
          echo "flux2=${FLUX2_VERSION}" >> $GITHUB_OUTPUT
      - name: Scan source-controller image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/source-controller:${{ steps.version.outputs.sc }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Scan kustomize-controller image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/kustomize-controller:${{ steps.version.outputs.kc }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Scan helm-controller image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/helm-controller:${{ steps.version.outputs.hc }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Scan notification-controller image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/notification-controller:${{ steps.version.outputs.nc }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Scan image-reflector-controller image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/image-reflector-controller:${{ steps.version.outputs.irc }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Scan image-automation-controller image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/image-automation-controller:${{ steps.version.outputs.iac }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Scan flux2 image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/weaveworks/flux-cli:${{ steps.version.outputs.flux2 }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
